services:
  web:
    build: .
    container_name: cloudcomp-app
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./database.sqlite:/var/www/html/database.sqlite
    restart: always
